// Code generated by qtc from "start.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:1
package templates

//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:1
import "net/http"

//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:2
import "ToDoTask/database"

//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:5
type StartPage struct {
	R    *http.Request
	Data []*database.ToDoItem
}

//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:11
func (p *StartPage) StreamTitle(qw422016 *qt422016.Writer) {
//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:11
	qw422016.N().S(`
	Main page
`)
//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:13
}

//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:13
func (p *StartPage) WriteTitle(qq422016 qtio422016.Writer) {
//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:13
	qw422016 := qt422016.AcquireWriter(qq422016)
//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:13
	p.StreamTitle(qw422016)
//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:13
	qt422016.ReleaseWriter(qw422016)
//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:13
}

//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:13
func (p *StartPage) Title() string {
//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:13
	qb422016 := qt422016.AcquireByteBuffer()
//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:13
	p.WriteTitle(qb422016)
//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:13
	qs422016 := string(qb422016.B)
//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:13
	qt422016.ReleaseByteBuffer(qb422016)
//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:13
	return qs422016
//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:13
}

//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:15
func (p *StartPage) StreamBody(qw422016 *qt422016.Writer) {
//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:15
	qw422016.N().S(`
	<h1>Main Page</h1>
	<div>
        Click links bellow
		<ul>
            <li><a href="/item-create">Create item</a></li>
        </ul>
	</div>

	<div>
		`)
//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:25
	if len(p.Data) > 0 {
//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:25
		qw422016.N().S(`
		<form action="/item-delete" method="post" enctype="multipart/form-data">
			<table border="1" cellpadding="10" align="center">
				<th>ID</th>
				<th>Title</th>
				<th>Category</th>
				<th>UserName</th>
				<th></th>
				`)
//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:33
		for _, item := range p.Data {
//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:33
			qw422016.N().S(`
					<tr>
						<td>`)
//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:35
			qw422016.N().D(int(item.ID))
//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:35
			qw422016.N().S(`</td>
						<td>`)
//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:36
			qw422016.E().S(string(item.Title))
//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:36
			qw422016.N().S(`</td>
						<td>`)
//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:37
			qw422016.E().S(item.Category)
//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:37
			qw422016.N().S(`</td>
						<td>`)
//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:38
			qw422016.E().S(item.UserName)
//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:38
			qw422016.N().S(`</td>
						<td><a href="/item-delete?id=`)
//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:39
			qw422016.N().D(int(item.ID))
//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:39
			qw422016.N().S(`">Delete</a></td>
					</tr>
				`)
//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:41
		}
//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:41
		qw422016.N().S(`
			</table>
		</form>	
		`)
//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:44
	} else {
//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:44
		qw422016.N().S(`
			<h5>No items currently exist</h5>
		`)
//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:46
	}
//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:46
	qw422016.N().S(`
	</div>
`)
//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:48
}

//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:48
func (p *StartPage) WriteBody(qq422016 qtio422016.Writer) {
//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:48
	qw422016 := qt422016.AcquireWriter(qq422016)
//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:48
	p.StreamBody(qw422016)
//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:48
	qt422016.ReleaseWriter(qw422016)
//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:48
}

//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:48
func (p *StartPage) Body() string {
//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:48
	qb422016 := qt422016.AcquireByteBuffer()
//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:48
	p.WriteBody(qb422016)
//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:48
	qs422016 := string(qb422016.B)
//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:48
	qt422016.ReleaseByteBuffer(qb422016)
//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:48
	return qs422016
//line C:/Users/vasil/go/src/ToDoTask/templates/start.qtpl:48
}
